defaults:
  - base

_target_: gflownet.policy.cnn.CNNPolicy

n_layers: 2
channels: [16, 32]
# Kernels: Each tuple represents (height, width)
kernels: [[3, 3], [2, 2]]
# Strides: Each tuple represents (vertical_stride, horizontal_stride)
strides: [[1, 1], [1, 1]]
