_target_: gflownet.proxy.box.corners.Corners

mu: 0.75
sigma: 0.05
do_gaussians: True
do_threshold: False
thresholds:
  - [0.0, 2.0, 1e-6]
  - [2.0, 3.0, 2.0]
  - [3.0, 100, 10.0]
scores:
  - 2.0
  - 0.5
  - 0.01
