defaults:
  - base

_target_: gflownet.envs.crystals.catalyst.Catalyst

id: catalyst

# Composition config
composition_kwargs:
  elements: 89

# Lattice parameters config
lattice_parameters_kwargs:
  min_length: 1.0
  max_length: 350.0
  min_angle: 50.0
  max_angle: 150.0

# Space group config
space_group_kwargs:
  space_groups_subset: null

# Miller indices config
miller_indices_kwargs:
  max_increment: 1
  max_dim_per_action: 1

# Composition or SpaceGroup first
do_sg_before_composition: False

# Constraints
do_composition_to_sg_constraints: True
do_sg_to_composition_constraints: True
do_sg_to_lp_constraints: True
do_sg_to_miller_constraints: True


# Buffer
buffer:
  data_path: null
  train: null
  test: null
