defaults:
  - base

_target_: gflownet.envs.crystals.lattice_parameters.LatticeParametersSGCCG

id: lattice_parameters_sgccg

# Lattice system
lattice_system: triclinic

# Policy
min_incr: 0.1
n_comp: 2
epsilon: 1e-6
beta_params_min: 0.1
beta_params_max: 100.0
fixed_distribution:
  beta_weights: 1.0
  beta_alpha: 10.0
  beta_beta: 10.0
  bernoulli_bts_prob: 0.1
  bernoulli_eos_prob: 0.1
random_distribution:
  beta_weights: 1.0
  beta_alpha: 10.0
  beta_beta: 10.0
  bernoulli_bts_prob: 0.1
  bernoulli_eos_prob: 0.1
