defaults:
  - base

_target_: gflownet.envs.crystals.mol_crystal.MolCrystal

# Composition parameters
id: mol_crystal
conditional: True
space_group_kwargs:
  generate_sgs: [2,14] # P-1 and P21/c - 'null' will generate in all space groups
lattice_parameters_kwargs:
  min_length: 0.25
  max_length: 3.0
  min_angle: 30.0
  max_angle: 150.0
  grid_size: 10
  min_position: 0.0 # fractional coordinates
  max_position: 1.0  # ideally grid should include exactly [0, .125, .25, .5]
  min_theta: 0.0
  max_theta: 90.0
  min_phi: -180.0
  max_phi: 180.0
  min_rotation: 0.0
  max_rotation: 360.0


# Buffer
buffer:
  data_path: null
  train:
    type: all
    output_csv: mol_crystal_train.csv
  test:
    type: all
    output_csv: mol_crystal_test.csv
