_target_: gflownet.policy.conformers.egnn.EGNNPolicy

shared:
  n_gnn_layers: 7
  n_mlp_layers: 2
  egnn_hidden_dim: 128
  mlp_hidden_dim: 256
  separate_mlp_per_torsion: True
  use_fake_edges: True
  fake_edge_radius: 2.0
forward: null
backward: null
