_target_: gflownet.policy.conformers.egnn.EGNNPolicy

forward:
  n_gnn_layers: 7
  n_node_mlp_layers: 2
  n_pool_mlp_layers: 2
  egnn_hidden_dim: 128
  node_mlp_hidden_dim: 128
  pool_mlp_hidden_dim: 128
backward:
  n_gnn_layers: 7
  n_node_mlp_layers: 2
  n_pool_mlp_layers: 2
  egnn_hidden_dim: 128
  node_mlp_hidden_dim: 128
  pool_mlp_hidden_dim: 128
