logdir:
  root: /network/scratch/h/hernanga/logs/gflownet
data:
  root: /home/mila/h/hernanga/gflownet/data
  alanine_dipeptide: /home/mila/h/hernanga/gflownet/data/alanine_dipeptide_conformers_1.npy
