logdir:
  root: /home/mkilgour/gflownet_data/logs  # todo automate clusterization
data:
  root: /home/mkilgour/gflownet_data/data

#logdir:
#  root: /scratch/mk8347/gflownet_data/logs
#data:
#  root: /scratch/mk8347/gflownet_data/data
