_wandb:
    value:
        cli_version: 0.22.1
        e:
            mv11245vi5oel88yqfkwxjrirhdopl85:
                args:
                    - env=investments
                    - proxy=uniform
                    - logger.do.online=True
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "994670800896"
                        used: "485839740928"
                email: jacopo.ghirri@gmail.com
                executable: C:\Users\jacop\Desktop\newsce\repos\gflownet\gflownet-env\Scripts\python.exe
                git:
                    commit: e25d1d738c6d44b6996d9280cc04cd3615cd2b84
                    remote: https://github.com/alexhernandezgarcia/gflownet.git
                gpu: NVIDIA GeForce RTX 4070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4608
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4070 Laptop GPU
                      uuid: GPU-d9f3bb95-a1f2-1cc1-4ccf-6157105d9ca0
                host: Jacopoli
                memory:
                    total: "34078003200"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\jacop\Desktop\newsce\repos\gflownet\train.py
                python: CPython 3.10.11
                root: C:\Users\jacop\Desktop\newsce\repos\gflownet
                startedAt: "2025-10-01T13:24:11.740174Z"
                writerId: mv11245vi5oel88yqfkwxjrirhdopl85
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 2
                - 13
                - 16
                - 18
                - 61
            "4": 3.10.11
            "5": 0.22.1
            "8":
                - 3
            "10":
                - 21
            "12": 0.22.1
            "13": windows-amd64
buffer:
    value:
        _target_: gflownet.buffer.base.BaseBuffer
        check_diversity: false
        diversity_check_reward_similarity: 0.1
        progress_process_dataset: false
        replay_buffer: null
        replay_capacity: 0
        test:
            "n": null
            path: null
            seed: null
            type: null
        train:
            "n": null
            path: null
            seed: null
            type: null
        use_main_buffer: false
device:
    value: cpu
env:
    value:
        _target_: gflownet.envs.investments.Single_Investment_DISCRETE
        conditional: false
        continuous: false
        env_id: env
        fixed_distr_params: null
        id: investments
        random_distr_params: null
        skip_mask_check: false
evaluator:
    value:
        _target_: gflownet.evaluator.base.BaseEvaluator
        checkpoints_period: 1000
        first_it: true
        kde:
            bandwidth: 0.1
            kernel: gaussian
        logprobs_batch_size: 100
        logprobs_bootstrap_size: 10000
        max_data_logprobs: 100000
        metrics: all
        "n": 100
        n_grid: 40000
        n_top_k: 5000
        n_trajs_logprobs: 10
        period: 100
        top_k: 100
        top_k_period: -1
        train_log_period: 1
float_precision:
    value: 32
gflownet:
    value:
        _target_: gflownet.gflownet.GFlowNetAgent
        collect_reversed_logprobs: false
        garbage_collection_period: 0
        mask_invalid_actions: true
        optimizer:
            adam_beta1: 0.9
            adam_beta2: 0.999
            batch_size:
                backward_dataset: 0
                backward_replay: 0
                forward: 10
            bootstrap_tau: 0
            clip_grad_norm: 0
            lr: 0.0001
            lr_decay_gamma: 0.5
            lr_decay_period: 1000000
            lr_z_mult: 10
            method: adam
            n_train_steps: 5000
            sgd_momentum: 0.9
            train_to_sample_ratio: 1
            z_dim: 16
        random_action_prob: 0
        replay_sampling: permutation
        seed: 0
        state_flow: null
        temperature_logits: 1
        train_sampling: permutation
        use_context: false
logger:
    value:
        _target_: gflownet.utils.logger.Logger
        context: "0"
        debug: false
        do:
            online: true
            times: false
        entity: null
        is_resumed: false
        lightweight: false
        logdir:
            ckpts: ckpts
            overwrite: true
            path: C:\Users\jacop\Desktop\newsce\repos\gflownet\logs\local\2025-10-01_09-24-10_493000
            root: ./logs
        notes: null
        progressbar:
            n_iters_mean: 100
            skip: false
        project_name: GFlowNet
        run_id: null
        run_name: null
        run_name_date: true
        run_name_job: true
        tags:
            - gflownet
loss:
    value:
        _target_: gflownet.losses.trajectorybalance.TrajectoryBalance
        early_stopping_th: 0
        ema_alpha: 0.5
n_samples:
    value: 1000
policy:
    value:
        _target_: gflownet.policy.base.Policy
        backward:
            checkpoint: null
            reload_ckpt: false
            shared_weights: true
        forward:
            checkpoint: null
            n_hid: 128
            n_layers: 2
            reload_ckpt: false
            type: mlp
        shared: null
proxy:
    value:
        _target_: gflownet.proxy.uniform.Uniform
        do_clip_rewards: false
        logreward_function: null
        reward_function: identity
        reward_min: 0
seed:
    value: 0
user:
    value:
        data:
            alanine_dipeptide: ~/gflownet/data/alanine_dipeptide_conformers_1.npy
            root: ./data
        logdir:
            root: ./logs
