defaults:
  - base

_target_: gflownet.envs.seqs.sequence.Sequence

id: sequence
# Tokens
tokens: [0, 1]
pad_token: -1
# Max length
max_length: 5
# Buffer
buffer:
  data_path: null
  train: null
  test:
    type: uniform
    n: 10
    output_csv: sequence_test.csv
    output_pkl: sequence_test.pkl
