defaults:
  - base

_target_: gflownet.envs.aptamer.Aptamer

id: aptamer
# Minimum and maximum length for the sequences
min_seq_length: 30
max_seq_length: 30
# Number of letters in alphabet
n_alphabet: 4
# Minimum and maximum number of steps in the action space
min_word_len: 1
max_word_len: 1
corr_type: None
