defaults:
  - base

_target_: gflownet.envs.ctorus.ContinuousTorus

id: ctorus
# Dimensions of hypertorus
n_dim: 2
policy_encoding_dim_per_angle: null
# Fixed length of trajectories
length_traj: 3
vonmises_min_concentration: 1e-3
# Parameters of the fixed policy output distribution
distr_type: von_mises
n_comp: 3
fixed_distr_params: null
random_distr_params: null