defaults:
  - _self_
  - user: default

# Path of a previous run to continue the training
# Training will continue from the latest checkpoints
rundir: null

# Print the configuration of the loaded run
print_config: False

# Disable wandb: if True, logging to wandb is disabled regardless of the configuration in
# the loaded run. Useful for debugging.
no_wandb: False

# Device
device: cpu
# Float precision
float_precision: 32
# Number of objects to sample at the end of training
n_samples: 1000
# Random seeds
seed: 0

# Hydra config
hydra:
  # See: https://hydra.cc/docs/configure_hydra/workdir/
  # See: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
  run:
    dir: ${rundir}/resume/${oc.env:SLURM_JOB_ID,local}/${now:%Y-%m-%d_%H-%M-%S_%f}
  sweep:
    dir: ${rundir}/resume/${oc.env:SLURM_JOB_ID,local}/multirun/${now:%Y-%m-%d_%H-%M-%S_%f}
  job:
    # See: https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir/
    # See: https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/#disable-changing-current-working-dir-to-jobs-output-dir
    chdir: True
