defaults:
  - base

_target_: gflownet.envs.iam.full_plan.FullPlan

id: full_plan

sectors: null
tags: null
techs: null
amounts: null
amount_values_mapping:
  HIGH: 0.75
  MEDIUM: 0.3
  LOW: 0.1
  NONE: 0.0
