shared:
  slurm: {}
  script:
    user: $USER
    device: cpu
    logger:
      project_name: gfn_sanity_checks
      do:
        online: True

jobs:
  # Grid
  - slurm:
      job_name: sanity-grid-fm
    script:
      env:
        __value__: grid
        length: 10
      buffer:
        test:
          type: all
      gflownet: flowmatch
      loss: flowmatching
      proxy: box/corners
      logger:
        run_name: Grid 10x10 FM
  - slurm:
      job_name: sanity-grid-tb
    script:
      env:
        __value__: grid
        length: 10
      buffer:
        test:
          type: all
      gflownet: trajectorybalance
      loss: trajectorybalance
      proxy: box/corners
      logger:
        run_name: Grid 10x10 TB
  - slurm:
      job_name: sanity-grid-db
    script:
      env:
        __value__: grid
        length: 10
      buffer:
        test:
          type: all
      gflownet: detailedbalance
      loss: detailedbalance
      proxy: box/corners
      logger:
        run_name: Grid 10x10 DB
  - slurm:
      job_name: sanity-grid-fl
    script:
      env:
        __value__: grid
        length: 10
      buffer:
        test:
          type: all
      gflownet: forwardlooking
      loss: forwardlooking
      proxy: box/corners
      logger:
        run_name: Grid 10x10 FL
  # Tetris
  - slurm:
      job_name: sanity-tetris-fm
    script:
      env:
        __value__: tetris
        width: 5
        height: 10
      buffer:
        test:
          type: random
          n: 10
      gflownet: flowmatch
      loss: flowmatching
      proxy: tetris
      evaluator:
        top_k: 10
        n_top_k: 100
      logger:
        run_name: Tetris 5x10 FM
  - slurm:
      job_name: sanity-tetris-tb
    script:
      env:
        __value__: tetris
        width: 5
        height: 10
      buffer:
        test:
          type: random
          n: 10
      gflownet: trajectorybalance
      loss: trajectorybalance
      proxy: tetris
      evaluator:
        top_k: 10
        n_top_k: 100
      logger:
        run_name: Tetris 5x10 TB
  # Ctorus
  - slurm:
      job_name: sanity-ctorus
    script:
      +experiments: icml23/ctorus
      buffer:
        test:
          type: grid
          n: 1000
      evaluator:
        period: 500
      logger:
        run_name: CTorus
