shared:
  slurm: {}
  script:
    user: $USER
    device: cpu
    logger:
      project_name: gfn_sanity_checks
      do:
        online: True

jobs:
  # Grid
  - slurm:
      job_name: sanity-grid-fm
    script:
      env:
        __value__: grid
        length: 10
      gflownet: flowmatch
      proxy: corners
  - slurm:
      job_name: sanity-grid-tb
    script:
      env:
        __value__: grid
        length: 10
      gflownet: trajectorybalance
      proxy: corners
  - slurm:
      job_name: sanity-grid-db
    script:
      env:
        __value__: grid
        length: 10
      gflownet: detailedbalance
      proxy: corners
  - slurm:
      job_name: sanity-grid-fl
    script:
      env:
        __value__: grid
        length: 10
      gflownet: forwardlooking
      proxy: corners
  # Tetris
  - slurm:
      job_name: sanity-tetris-fm
    script:
      env:
        __value__: tetris
        width: 5
        height: 10
      gflownet: flowmatch
      proxy: tetris
      evaluator:
        top_k: 10
        n_top_k: 100
  - slurm:
      job_name: sanity-tetris-tb
    script:
      env:
        __value__: tetris
        width: 5
        height: 10
      gflownet: trajectorybalance
      proxy: tetris
      evaluator:
        top_k: 10
        n_top_k: 100
  # Mini-Tetris
  - slurm:
      job_name: sanity-mintetris-fm
    script:
      env:
        __value__: tetris
        width: 3
        height: 10
        pieces: ["J", "L", "S", "Z"]
        allow_eos_before_full: True
      proxy:
        __value__: tetris
        reward_function: exponential
      gflownet: flowmatch
      evaluator:
        top_k: 10
        n_top_k: 100
  - slurm:
      job_name: sanity-mintetris-tb
    script:
      env:
        __value__: tetris
        width: 3
        height: 10
        pieces: ["J", "L", "S", "Z"]
        allow_eos_before_full: True
      proxy:
        __value__: tetris
        reward_function: exponential
      gflownet: trajectorybalance
      evaluator:
        top_k: 10
        n_top_k: 100
  - slurm:
      job_name: sanity-mintetris-fl
    script:
      env:
        __value__: tetris
        width: 3
        height: 10
        pieces: ["J", "L", "S", "Z"]
        allow_eos_before_full: True
      proxy:
        __value__: tetris
        reward_function: exponential
      gflownet: forwardlooking
      evaluator:
        top_k: 10
        n_top_k: 100
  # Ctorus
  - slurm:
      job_name: sanity-ctorus
    script:
      +experiments: icml23/ctorus
      evalutor:
        period: 500
