shared:
  slurm: {}
  script:
    user: $USER
    device: cpu
    logger:
      project_name: gfn_sanity_checks
      do:
        online: True

jobs:
  # Grid
  - slurm:
      job_name: sanity-grid-fm
    script:
      env:
        __value__: grid
        length: 10
      gflownet: flowmatch
  - slurm:
      job_name: sanity-grid-tb
    script:
      env:
        __value__: grid
        length: 10
      gflownet: trajectorybalance
  - slurm:
      job_name: sanity-grid-db
    script:
      env:
        __value__: grid
        length: 10
      gflownet: detailedbalance
  - slurm:
      job_name: sanity-grid-fl
    script:
      env:
        __value__: grid
        length: 10
      gflownet: forwardlooking
  # Tetris
  - slurm:
      job_name: sanity-tetris-fm
    script:
      env:
        __value__: tetris
        width: 5
        height: 10
      gflownet: flowmatch
      proxy: tetris
  - slurm:
      job_name: sanity-tetris-tb
    script:
      env:
        __value__: tetris
        width: 5
        height: 10
      gflownet: trajectorybalance
      proxy: tetris
  # Mini-Tetris
  - slurm:
      job_name: sanity-mintetris-fm
    script:
      env:
        __value__: tetris
        width: 3
        height: 10
        pieces: ["J", "L", "S", "Z"]
        allow_eos_before_full: True
        reward_func: boltzmann
      gflownet: flowmatch
      proxy: tetris
  - slurm:
      job_name: sanity-mintetris-tb
    script:
      env:
        __value__: tetris
        width: 3
        height: 10
        pieces: ["J", "L", "S", "Z"]
        allow_eos_before_full: True
        reward_func: boltzmann
      gflownet: trajectorybalance
      proxy: tetris
  - slurm:
      job_name: sanity-mintetris-fl
    script:
      env:
        __value__: tetris
        width: 3
        height: 10
        pieces: ["J", "L", "S", "Z"]
        allow_eos_before_full: True
        reward_func: boltzmann
      gflownet: forwardlooking
      proxy: tetris
  # Ctorus
  - slurm:
      job_name: sanity-ctorus
    script:
      +experiments: icml23/ctorus
