defaults:
  - base

_target_: gflownet.utils.vislogger.logger.VisLogger

vislogger:
  use: True
  # Logs the batch of the training batchsize every n iterations
  log_every_n: 10
  # Shows the dashboard during training (not fully implemented yet)
  show_during_training: False
  # Launches the dashboard after training
  launch_after_training: False


tags:
    - gflownet